"""Seed de Tipos e Motivos de Ocorrência para o SAMU."""
from app import db
from app.models.tipo_ocorrencia import TipoOcorrencia
from app.models.motivo_ocorrencia import MotivoOcorrencia

TIPOS = [
    'Clínico',
    'Pediátrico',
    'Causas externas',
    'Gineco-obstétrico',
    'Psiquiátrico',
    'Cirúrgico',
    'Oncológico',
]

# Mapeamento do nome no CSV para o nome no BD (só primeira maiúscula)
TIPO_MAP = {
    'CLINICO': 'Clínico',
    'PEDIATRICO': 'Pediátrico',
    'CAUSAS EXTERNAS': 'Causas externas',
    'GINECO-OBSTÉTRICO': 'Gineco-obstétrico',
    'PSIQUIÁTRICO': 'Psiquiátrico',
    'CIRÚRGICO': 'Cirúrgico',
    'ONCOLÓGICO': 'Oncológico',
}

MOTIVOS_RAW = """CLINICO	AGITAÇÃO
CLINICO	ALERGIA/URTICÁRIA/PRURIDO
CLINICO	ANÚRIA
CLINICO	ARRITIMIA
CLINICO	ASCITE
CLINICO	ASFIXIA
CLINICO	CARDIO/CRISE HIPERTENSIVA/HAS
CLINICO	CARDIO/INSUF. CARDIACA CONGESTIVA
CLINICO	CARDIO/OUTROS
CLINICO	CARDIO/PCR
CLINICO	CARDIO/SCA (AI/IAM)
CLINICO	CEFALÉIA
CLINICO	CHOQUE CARDIOGÊNICO
CLINICO	CHOQUE HIPOVOLÊMICO
CLINICO	COLICA RENAL
CLINICO	CONVULSÕES FEBRIS
CLINICO	CRISE CONVULSIVA
CLINICO	DESIDRATAÇÃO
CLINICO	DIGESTIVA/DIARRÉIA E VÔMITOS
CLINICO	DIMINUIÇÃO DO NÍVEL DE CONSCIÊNCIA
CLINICO	DISPNÉIA
CLINICO	DISÚRIA
CLINICO	DOR ANAL
CLINICO	DOR CERVICAL
CLINICO	DOR DE GARGANTA
CLINICO	DOR GENITAL
CLINICO	DOR PÉLVICA E PERINEAL
CLINICO	DOR TORÁCICA
CLINICO	EPIGASTRALGIA
CLINICO	EPISTAXE
CLINICO	ERITEMA, ERUPÇÕES CUTÂNEAS
CLINICO	FEBRE
CLINICO	FERIDAS
CLINICO	FERIMENTO ABDOME
CLINICO	FERIMENTO CABEÇA
CLINICO	FERIMENTO CERVICAL
CLINICO	FERIMENTO DORSO E PELVE
CLINICO	FERIMENTO MEMBROS INFERIORES MMII
CLINICO	FERIMENTO MEMBROS SUPERIORES MMSS
CLINICO	FERIMENTO TÓRAX
CLINICO	FERIMENTOS MÚLTIPLOS
CLINICO	FRATURA ÓSSEA
CLINICO	GRIPE A
CLINICO	HEMATÚRIA
CLINICO	HEMOPTISE
CLINICO	HIPERGLICEMIA
CLINICO	HIPOGLICEMIA
CLINICO	HIPOTENSÃO
CLINICO	HIPOTERMIA
CLINICO	ICTERÍCIA
CLINICO	INFECTO/AIDS
CLINICO	INFECTO/OUTROS
CLINICO	INFECTO/TUBERCULOSE
CLINICO	INGESTÃO DE CORPÓ ESTRANHO
CLINICO	INSUFICIÊNCIA RESPIRATÓRIA
CLINICO	INTOXIÇÃO EXÓGENA
CLINICO	LOMBALGIA
CLINICO	MORTE SEM ASSISTÊNCIA, ÓBITO
CLINICO	MORTE SÚBITA
CLINICO	MORTE SÚBITA NA INFÂNCIA
CLINICO	NEFRO/IRC
CLINICO	NEOPLASIA/ESCLARECER
CLINICO	NEURO/AVC
CLINICO	NEURO/SEQUELADOS OU ACAMADOS
CLINICO	ÓBITO
CLINICO	OTALGIA
CLINICO	POLIÚRIA
CLINICO	QUEIXAS OCULARES
CLINICO	RESPIRATÓRIO/ASMA
CLINICO	RESPIRATÓRIO/PNEUMONIA
CLINICO	RETENÇÃO URINÁRIA
CLINICO	SÍNCOPE/DESMAIO
CLINICO	SOLUÇO
CLINICO	TONTURAS
CLINICO	RETORNO DOMICILIAR
CLINICO	TRANSFERÊNCIA INTER-HOSPITALAR
PEDIATRICO	CIANOSE
PEDIATRICO	CONSTIPAÇÃO
PEDIATRICO	CONVULSÃO
PEDIATRICO	CRISE DE CHORO
PEDIATRICO	DESIDRTAÇÃO
PEDIATRICO	DIARRÉIA
PEDIATRICO	DISPNÉIA
PEDIATRICO	DISTENSÃO ABDOMINAL
PEDIATRICO	DISÚRIA
PEDIATRICO	DOR
PEDIATRICO	DOR ABDOMINAL
PEDIATRICO	DOR DE GARGANTA
PEDIATRICO	EXANTEMA
PEDIATRICO	FEBRE
PEDIATRICO	FERIDAS
PEDIATRICO	HEMATURIA
PEDIATRICO	HEMORRAGIA
PEDIATRICO	INF. EM CORDÃO UMBILICAL
PEDIATRICO	INGESTAO DE CORPO ESTRANHO
PEDIATRICO	INTOXICAÇÃO EXÓGENA
PEDIATRICO	ÓBITO
PEDIATRICO	OBSTRUÇÃO NASAL
PEDIATRICO	PALIDEZ
PEDIATRICO	PERDA PONDERAL
PEDIATRICO	PRURIDO
PEDIATRICO	QUEIMADURA
PEDIATRICO	SUDORESE
PEDIATRICO	TOSSE
PEDIATRICO	VÔMITO
CAUSAS EXTERNAS	ACIDENTE ANIMAL PEÇONHENTO
CAUSAS EXTERNAS	ACIDENTE ANIMAL/MORDEDURA
CAUSAS EXTERNAS	Acidente com transporte ferroviário
CAUSAS EXTERNAS	ACIDENTE RADIAÇÃO IONIZANTE
CAUSAS EXTERNAS	ACIDENTE TRABALHO
CAUSAS EXTERNAS	ACIDENTE TRANSPORTE AÉREO
CAUSAS EXTERNAS	AFOGAMENTO
CAUSAS EXTERNAS	AGRESSÃO
CAUSAS EXTERNAS	AGRESSAO SEXUAL
CAUSAS EXTERNAS	Amputação
CAUSAS EXTERNAS	Apoio a alagamento
CAUSAS EXTERNAS	Apoio a incêndio
CAUSAS EXTERNAS	ASPIRAÇÃO CONTEÚDO GÁSTRICO/CE
CAUSAS EXTERNAS	ATROPELAMENTO POR BICICLETA
CAUSAS EXTERNAS	ATROPELAMENTO POR CAMINHÃO
CAUSAS EXTERNAS	ATROPELAMENTO POR CARRO
CAUSAS EXTERNAS	ATROPELAMENTO POR MOTO
CAUSAS EXTERNAS	ATROPELAMENTO POR ÔNIBUS
CAUSAS EXTERNAS	ATROPELAMENTO POR TREM
CAUSAS EXTERNAS	CAPOTAGEM DE VEÍCULO
CAUSAS EXTERNAS	CHOQUE ELÉTRICO
CAUSAS EXTERNAS	COLISÃO ANIMAL X BICICLETA
CAUSAS EXTERNAS	COLISÃO ANIMAL X CARRO
CAUSAS EXTERNAS	COLISÃO ANIMAL X MOTO
CAUSAS EXTERNAS	COLISÃO CARRO X BICICLETA
CAUSAS EXTERNAS	COLISÃO CARRO X CAMINHÃO
CAUSAS EXTERNAS	COLISÃO CARRO X CARRO
CAUSAS EXTERNAS	COLISÃO CARRO X MOTO
CAUSAS EXTERNAS	COLISÃO CARRO X MURO/POSTE
CAUSAS EXTERNAS	COLISÃO CARRO X ÔNIBUS
CAUSAS EXTERNAS	COLISÃO CARRO X TREM
CAUSAS EXTERNAS	COLISÃO MOTO X CAMINHÃO
CAUSAS EXTERNAS	COLISÃO MOTO X MOTO
CAUSAS EXTERNAS	COLISÃO OUTROS
CAUSAS EXTERNAS	DESABAMENTO
CAUSAS EXTERNAS	DESMORONAMENTO
CAUSAS EXTERNAS	ENFORCAMENTO
CAUSAS EXTERNAS	ENTORSE/LUXAÇÃO
CAUSAS EXTERNAS	EXPLOSÃO
CAUSAS EXTERNAS	FERIMENTO ARMA BRANCA
CAUSAS EXTERNAS	FERIMENTO ARMA DE FOGO
CAUSAS EXTERNAS	FERIMENTO CONTUSO
CAUSAS EXTERNAS	QUEDA > 3 METROS
CAUSAS EXTERNAS	QUEDA ALTURA
CAUSAS EXTERNAS	QUEDA DE BICICLETA
CAUSAS EXTERNAS	QUEDA DE MOTO
CAUSAS EXTERNAS	QUEDA PRÓPRIA ALTURA
CAUSAS EXTERNAS	QUEIMADURA
CAUSAS EXTERNAS	QUEIMADURA POR AGUA QUENTE
CAUSAS EXTERNAS	QUEIMADURA POR ALCOOL
CAUSAS EXTERNAS	QUEIMADURA POR FOGOS DE ARTIFICIO
CAUSAS EXTERNAS	EVENTO COM MÚLTIPLAS VÍTIMAS
CAUSAS EXTERNAS	APOIO A FORÇA DE SEGURANÇA
GINECO-OBSTÉTRICO	ABORTAMENTO
GINECO-OBSTÉTRICO	AMNIORREXE PREMATURA
GINECO-OBSTÉTRICO	DOENÇA HIPERTENSIVA GESTACIONAL
GINECO-OBSTÉTRICO	ECLÂMPSIA/PRÉ-ECLÂMPSIA
GINECO-OBSTÉTRICO	GINECO/NEOPLASIA
GINECO-OBSTÉTRICO	GINECO/SANGRAMENTO UTERINO
GINECO-OBSTÉTRICO	HEMORRAGIA DISFUNCIONAL
GINECO-OBSTÉTRICO	HIPEREMESE GRAVÍDICA
GINECO-OBSTÉTRICO	INFECÇÃO / DIP
GINECO-OBSTÉTRICO	PARTO CONSUMADO/NÃO HOSPITALAR
GINECO-OBSTÉTRICO	TRABALHO DE PARTO
GINECO-OBSTÉTRICO	TRABALHO DE PARTO PREMATURO
PSIQUIÁTRICO	ABUSO DE ÁLCOOL
PSIQUIÁTRICO	ABUSO DE DROGAS
PSIQUIÁTRICO	CRISE CONVERSIVA
PSIQUIÁTRICO	DEPRESSÃO
PSIQUIÁTRICO	ESQUIZOFRENIA
PSIQUIÁTRICO	IDEAÇÃO SUICIDA
PSIQUIÁTRICO	SURTO PSICÓTICO
PSIQUIÁTRICO	TENTATIVA DE HOMICÍDIO
PSIQUIÁTRICO	TENTATIVA DE SUICÍDIO
PSIQUIÁTRICO	TRANSTORNO ANSIOSO (ANSIEDADE E SIND. PÂNICO)
PSIQUIÁTRICO	ATENDIMENTO PSIQUIÁTRICO INVOLUNTÁRIO
CIRÚRGICO	ABDOME AGUDO HEMORRÁGICO
CIRÚRGICO	ABDOME INFLAMATÓRIO
CIRÚRGICO	ABDOME OBSTRUTIVO
CIRÚRGICO	DOR ABDOMINAL A ESCLARECER
CIRÚRGICO	HEMORRAGIA DIGESTIVA
CIRÚRGICO	INFECÇÃO PÓS OPERATÓRIA
CIRÚRGICO	OBSTRUÇÕES VASCULARES
ONCOLÓGICO	ATENDIMENTO A PACIENTE EM CUIDADOS PALIATIVOS
"""


def _titulo(s):
    """Primeira letra maiúscula, resto minúsculo."""
    if not s or not s.strip():
        return s
    return s.strip()[0].upper() + s.strip()[1:].lower()


def run_seed(app):
    """Executa o seed de tipos e motivos."""
    with app.app_context():
        # 1. Criar ou obter tipos
        tipos_by_nome = {}
        for nome in TIPOS:
            t = TipoOcorrencia.query.filter_by(nome=nome).first()
            if not t:
                t = TipoOcorrencia(nome=nome, ativo=True)
                db.session.add(t)
                db.session.flush()
            tipos_by_nome[nome] = t
        db.session.commit()

        # 2. Criar motivos (evitar duplicatas por nome+tipo)
        criados = 0
        for linha in MOTIVOS_RAW.strip().split('\n'):
            linha = linha.strip()
            if not linha:
                continue
            parts = linha.split('\t', 1)
            if len(parts) != 2:
                continue
            tipo_key, motivo_raw = parts[0].strip(), parts[1].strip()
            tipo_nome = TIPO_MAP.get(tipo_key.upper(), tipo_key)
            motivo_nome = _titulo(motivo_raw)  # primeira maiúscula
            tipo_obj = tipos_by_nome.get(tipo_nome)
            if not tipo_obj:
                continue
            existe = MotivoOcorrencia.query.filter_by(
                nome=motivo_nome, tipo_ocorrencia_id=tipo_obj.id
            ).first()
            if not existe:
                m = MotivoOcorrencia(
                    nome=motivo_nome,
                    tipo_ocorrencia_id=tipo_obj.id,
                    ativo=True
                )
                db.session.add(m)
                criados += 1
        db.session.commit()
        return {'tipos': len(TIPOS), 'motivos_criados': criados}
